name: Prettier

on:
  pull_request:
    branches: [ main ]

jobs:
  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm install
      - name: Check formatting
        run: npx prettier --check .
      - name: Fail if there are unformatted files
        run: if [ -n "$(git status --porcelain)" ]; then git diff; exit 1; fi
